import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | MP3toMIDI",
  description:
    "Privacy Policy for mp3tomidi.vip — learn how we handle your data. Your audio never leaves your device.",
  robots: { index: false, follow: true },
};

export default function PrivacyPage() {
  return (
    <div className="legal-page">
      <header className="legal-header">
        <div className="container">
          <h1>Privacy Policy</h1>
          <p className="legal-updated">Last updated: July 17, 2026</p>
        </div>
      </header>
      <main className="legal-content container">
        <section>
          <h2>Introduction</h2>
          <p>
            mp3tomidi.vip (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;)
            operates the mp3tomidi.vip website (the &quot;Service&quot;). This
            page informs you of our policies regarding the collection, use, and
            disclosure of personal information when you use our Service.
          </p>
        </section>

        <section>
          <h2>Information Collection and Use</h2>

          <h3>Audio Files</h3>
          <p>
            <strong>
              We do not collect, store, or transmit your audio files.
            </strong>{" "}
            All audio processing occurs entirely within your web browser using
            client-side technology. Your audio files never leave your device.
          </p>

          <h3>Log Data</h3>
          <p>
            We may collect information that your browser sends whenever you
            visit our Service (&quot;Log Data&quot;). This Log Data may include
            information such as your computer&apos;s Internet Protocol
            (&quot;IP&quot;) address, browser type, browser version, the pages
            of our Service that you visit, the time and date of your visit, the
            time spent on those pages, and other statistics.
          </p>

          <h3>Analytics</h3>
          <p>
            We use third-party analytics services to monitor and analyze the use
            of our Service:
          </p>
          <ul>
            <li>
              <strong>Google Analytics 4</strong>: Web analytics service provided
              by Google. Google Analytics uses cookies to help us analyze how
              users use the Service. The information generated by the cookie
              about your use of the Service will be transmitted to and stored by
              Google on servers in the United States. Google Analytics anonymizes
              IP addresses by default.
            </li>
            <li>
              <strong>Microsoft Clarity</strong>: Heatmap and session recording
              service provided by Microsoft. Clarity helps us understand how
              users interact with our Service. Clarity does not collect personal
              information and anonymizes IP addresses.
            </li>
          </ul>

          <h3>Cookies</h3>
          <p>
            Cookies are files with a small amount of data, which may include an
            anonymous unique identifier. Cookies are sent to your browser from a
            web site and stored on your computer&apos;s hard drive.
          </p>
          <p>We use cookies to:</p>
          <ul>
            <li>Analyze usage patterns (Google Analytics, Microsoft Clarity)</li>
            <li>Remember your preferences</li>
          </ul>
          <p>
            You can instruct your browser to refuse all cookies or to indicate
            when a cookie is being sent. However, if you do not accept cookies,
            you may not be able to use some portions of our Service.
          </p>
        </section>

        <section>
          <h2>Use of Information</h2>
          <p>
            We use the collected information for the following purposes:
          </p>
          <ul>
            <li>To provide and maintain our Service</li>
            <li>To notify you about changes to our Service</li>
            <li>
              To allow you to participate in interactive features of our Service
            </li>
            <li>To provide customer support</li>
            <li>
              To gather analysis or valuable information so that we can improve
              our Service
            </li>
            <li>To monitor the usage of our Service</li>
            <li>To detect, prevent and address technical issues</li>
          </ul>
        </section>

        <section>
          <h2>Data Security</h2>
          <p>
            The security of your data is important to us, but remember that no
            method of transmission over the Internet, or method of electronic
            storage, is 100% secure. While we strive to use commercially
            acceptable means to protect your personal information, we cannot
            guarantee its absolute security.
          </p>
        </section>

        <section>
          <h2>Service Providers</h2>
          <p>
            We may employ third party companies and individuals to facilitate
            our Service, to provide the Service on our behalf, to perform
            Service-related services, or to assist us in analyzing how our
            Service is used.
          </p>
          <p>
            These third parties have access to your personal information only to
            perform these tasks on our behalf and are obligated not to disclose
            or use it for any other purpose.
          </p>
        </section>

        <section>
          <h2>Links to Other Sites</h2>
          <p>
            Our Service may contain links to other sites that are not operated
            by us. If you click on a third party link, you will be directed to
            that third party&apos;s site. We strongly advise you to review the
            Privacy Policy of every site you visit.
          </p>
          <p>
            We have no control over, and assume no responsibility for the
            content, privacy policies, or practices of any third party sites or
            services.
          </p>
        </section>

        <section>
          <h2>Children&apos;s Privacy</h2>
          <p>
            Our Service does not address anyone under the age of 13
            (&quot;Children&quot;). We do not knowingly collect personally
            identifiable information from children under 13. If you are a parent
            or guardian and you are aware that your Children have provided us
            with personal information, please contact us. If we discover that a
            child under 13 has provided us with personal information, we will
            delete such information from our servers immediately.
          </p>
        </section>

        <section>
          <h2>Changes to This Privacy Policy</h2>
          <p>
            We may update our Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on this page.
          </p>
          <p>
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </p>
        </section>

        <section>
          <h2>Contact Us</h2>
          <p>
            If you have any questions about this Privacy Policy, please contact
            us at: <a href="mailto:contact@mp3tomidi.vip">contact@mp3tomidi.vip</a>
          </p>
        </section>
      </main>
    </div>
  );
}
