import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | MP3toMIDI",
  description:
    "Terms of Service for mp3tomidi.vip — read the rules for using our free MP3 to MIDI converter.",
  robots: { index: false, follow: true },
};

export default function TermsPage() {
  return (
    <div className="legal-page">
      <header className="legal-header">
        <div className="container">
          <h1>Terms of Service</h1>
          <p className="legal-updated">Last updated: July 17, 2026</p>
        </div>
      </header>
      <main className="legal-content container">
        <section>
          <h2>Introduction</h2>
          <p>
            Welcome to mp3tomidi.vip (&quot;we&quot;, &quot;us&quot;, or
            &quot;our&quot;). By accessing or using our website mp3tomidi.vip
            (the &quot;Service&quot;), you agree to be bound by these Terms of
            Service (&quot;Terms&quot;). If you disagree with any part of the
            Terms, then you may not access the Service.
          </p>
        </section>

        <section>
          <h2>Use of Service</h2>

          <h3>Free Service</h3>
          <p>
            mp3tomidi.vip provides a free online tool for converting audio files
            to MIDI format. The Service is provided &quot;as is&quot; and
            &quot;as available&quot; without warranties of any kind.
          </p>

          <h3>User Responsibilities</h3>
          <p>By using our Service, you agree to:</p>
          <ol>
            <li>
              <strong>Upload only content you have the right to use</strong>:
              You must own or have legal permission to upload any audio files to
              our Service.
            </li>
            <li>
              <strong>Not upload illegal content</strong>: You must not upload
              any content that is illegal, harmful, threatening, abusive,
              harassing, defamatory, vulgar, obscene, or otherwise
              objectionable.
            </li>
            <li>
              <strong>Not abuse the Service</strong>: You must not attempt to
              disrupt, overload, or interfere with the Service.
            </li>
            <li>
              <strong>Comply with applicable laws</strong>: You must use the
              Service in compliance with all applicable local, state, national,
              and international laws.
            </li>
          </ol>

          <h3>No Registration Required</h3>
          <p>
            Our Service does not require user registration or account creation.
            All processing occurs anonymously.
          </p>
        </section>

        <section>
          <h2>Intellectual Property</h2>

          <h3>Our Content</h3>
          <p>
            The Service and its original content, features, and functionality
            are owned by mp3tomidi.vip and are protected by international
            copyright, trademark, patent, trade secret, and other intellectual
            property or proprietary rights laws.
          </p>

          <h3>Your Content</h3>
          <p>
            You retain all rights to any audio files you upload to our Service.
            We do not claim any ownership over your content. Since all
            processing occurs in your browser, we never have access to your
            audio files.
          </p>

          <h3>Generated MIDI Files</h3>
          <p>
            MIDI files generated by our Service are provided to you for your
            use. You are responsible for ensuring that your use of generated
            MIDI files complies with applicable copyright laws.
          </p>
        </section>

        <section>
          <h2>Disclaimer of Warranties</h2>
          <p>
            THE SERVICE IS PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS
            AVAILABLE&quot; BASIS. WE EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY
            KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
            IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
            PURPOSE, AND NON-INFRINGEMENT.
          </p>
          <p>WE DO NOT WARRANT THAT:</p>
          <ul>
            <li>
              THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE
            </li>
            <li>
              THE RESULTS OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE
              OR RELIABLE
            </li>
            <li>
              THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER
              MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL
              MEET YOUR EXPECTATIONS
            </li>
          </ul>
        </section>

        <section>
          <h2>AI Processing Disclaimer</h2>
          <p>
            Our Service uses artificial intelligence (AI) technology to convert
            audio files to MIDI format. By using our Service, you acknowledge
            and agree that:
          </p>
          <ol>
            <li>
              <strong>AI-generated results may not be perfect</strong>: The
              conversion process uses AI algorithms that may not always produce
              accurate or complete results.
            </li>
            <li>
              <strong>Results vary by input quality</strong>: The quality of the
              conversion depends on the quality, clarity, and complexity of the
              input audio file.
            </li>
            <li>
              <strong>No guarantee of accuracy</strong>: We do not guarantee
              that the generated MIDI files will accurately represent the
              original audio.
            </li>
            <li>
              <strong>Manual review recommended</strong>: We recommend reviewing
              and editing generated MIDI files before using them in professional
              or commercial contexts.
            </li>
            <li>
              <strong>AI technology limitations</strong>: Current AI technology
              has limitations and may not correctly transcribe complex
              arrangements, multiple instruments, or low-quality audio.
            </li>
          </ol>
        </section>

        <section>
          <h2>Limitation of Liability</h2>
          <p>
            IN NO EVENT SHALL MP3TOMIDI.VIP, NOR ITS DIRECTORS, EMPLOYEES,
            PARTNERS, AGENTS, SUPPLIERS, OR AFFILIATES, BE LIABLE FOR ANY
            INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES,
            INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL,
            OR OTHER INTANGIBLE LOSSES, RESULTING FROM:
          </p>
          <ul>
            <li>
              YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE
            </li>
            <li>ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICE</li>
            <li>ANY CONTENT OBTAINED FROM THE SERVICE</li>
            <li>
              UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR
              CONTENT
            </li>
          </ul>
        </section>

        <section>
          <h2>Changes to Terms</h2>
          <p>
            We reserve the right to modify or replace these Terms at any time.
            If a revision is material, we will try to provide at least 30
            days&apos; notice prior to any new terms taking effect. What
            constitutes a material change will be determined at our sole
            discretion.
          </p>
        </section>

        <section>
          <h2>Contact Us</h2>
          <p>
            If you have any questions about these Terms, please contact us at:{" "}
            <a href="mailto:contact@mp3tomidi.vip">contact@mp3tomidi.vip</a>
          </p>
        </section>
      </main>
    </div>
  );
}
